services:
  - type: web
    name: nybot-host
    runtime: node
    plan: starter
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
